apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: UK2CNC5WACG6WIRXXP6M
  secretAccessKey: JEL4R2zaoDmanv6cLLNhwvzEkaD5ZAxvFhWKV7D5
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://10.1.0.15:30260
  # If not on S3, set it to ""
  region: ""
