apiVersion: v1
kind: Pod
metadata:
  name: cephfs-test-nginx
  namespace: default
spec:
  containers:
   - name: cephfs-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/www/html
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: cephfs-pvc
       readOnly: false
